name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}

      - name: Bump version and push tag
        uses: naga1090/github-bump-tag-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
